### PR TITLE
Configure whitenoise so that it really does serve the static files.

### PR DESCRIPTION
**Pull request by benroy73**
This is more important in Angular apps but it should at least work here too.

### CODE REVIEW

**Review by silby — CHANGES_REQUESTED** [review]
plz note in a comment what the magic number `31536000` is in smaller units

**Comment by silby** [comment]
Why such a long `max_age`? The default is 60 seconds. It seems like far-future caching should be reserved for built assets with unique names, if I'm [reading the documentation correctly](http://whitenoise.evans.io/en/stable/base.html#caching-headers). I don't think setting the max age that high for everything in `static` will have good results.

**Comment by benroy73** [comment]
I uncertain about what will really happen so I think you're right. I'm a bit conflicted about just leaving it out of this example and letting it default to 60s or setting it to the 12h that flask does by default without whitenoise.

MDN [has examples](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) showing a whole other set of choices to get the clients to cache but revalidate. I think that's really what we want in the flask apps (cache and revalidate).

Adding a simple asset pipeline to pre-compress and version the static assets is really what we should do to optimise whitenoise, but that's a future improvement to consider along with HTTP/2 support.

**Comment by benroy73** [comment]
After a closer examination of what is working now in MCI now I think the default 60s will be fine.
In MCI we are already getting HTTP/2 and gzip compression for Flask apps and the shared static files.
Looking at these in the web inspector it's clear that the HTTP/2 multiplexing and pipelining are very effective already.
https://barista.s.uw.edu/ipfo/
https://barista.s.uw.edu/shared/local/core/6.2.0/

With the JS frameworks already doing their own asset bundling I think we're in a good performance place on MCI.

**Review by silby — APPROVED** [review]
cool, thanks for getting clear on that, lgtm.

**Review by atomiro — APPROVED** [review]

**Review by guywilsonjr — APPROVED** [review]

**Pull request merged**
